language: node_js
sudo: required
cache: yarn
env:
  global:
  - ENCRYPTION_LABEL: "b601314e09dc"
  - COMMIT_AUTHOR_EMAIL: "jdh.schuler@gmail.com"
  - COMMIT_AUTHOR_USERNAME: "jschuler"
  - TRIGGER_REPO_SLUG: "pfbreakaway/breakaway-patternfly-react"
  - TRIGGER_REPO_BRANCH: "master"
notifications:
  email: false
before_install:
- npm install --global surge
- .travis/before_install.sh
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn install
script:
- yarn build
# - yarn test
- yarn coveralls
after_success:
- .travis/after_success.sh
- .travis/release.sh
- chmod ugo+x ./.travis/deploy_pr.sh
# - .travis/deploy_pr.sh
git:
  depth: 1
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: surge
  project: ./.public/
  domain: breakaway-patternfly-react.surge.sh
  skip_cleanup: true
